export enum CurrencyCodeEnum {
  UAH = 'uah',
  EUR = 'eur',
  USD = 'usd'
}

export const DEFAULT_CURRENCY: CurrencyCodeEnum = CurrencyCodeEnum.UAH;

const a = {
  'entity_id': 562,
  'attribute_set_id': 14,
  'type_id': 'simple',
  'brush_material': null,
  'brush_material_value': null,
  'cadence_color_metallic': null,
  'cadence_color_metallic_value': null,
  'color': 468,
  'color_value': 'Белое золото',
  'color_bitum': null,
  'color_bitum_value': null,
  'color_ghidkaya_potal_ferrario': null,
  'color_ghidkaya_potal_ferrario_value': null,
  'color_ghidkaya_potal_kreul': null,
  'color_ghidkaya_potal_kreul_value': null,
  'color_kraska_premium_paint': null,
  'color_kraska_premium_paint_value': null,
  'color_kroshka_groft': null,
  'color_kroshka_groft_value': null,
  'color_patina_cadence_antique': null,
  'color_patina_cadence_antique_value': null,
  'color_patina_cadence_distress': null,
  'color_patina_cadence_distress_value': null,
  'color_patina_cadence_rusty': null,
  'color_patina_cadence_rusty_value': null,
  'color_pigment': null,
  'color_pigment_value': null,
  'color_potal': null,
  'color_potal_value': null,
  'color_varnish': null,
  'color_varnish_value': null,
  'color_voska': null,
  'color_voska_value': null,
  'cost': null,
  'created_at': '2019-07-27 22:10:13',
  'cvet_akrilovoj_kraski_kadens_m': null,
  'cvet_akrilovoj_kraski_kadens_m_value': null,
  'cvet_zhidkoj_potali_renessans': null,
  'cvet_zhidkoj_potali_renessans_value': null,
  'description': '<p><strong><em>Сусальное золото отправляется только по полной предоплате.</em></strong></p>\r\n<p><strong><em>На этот товар скидки не распространяются.</em></strong></p>\r\n<p><span><em>Следует  учесть что фотоаппарат и монитор могут не в полной мере передавать цвет и оттенок, поэтому цвет товара может отличаться от увиденного Вами на экране.</em></span></p>\r\n<p><span><strong><em>Сусаль отправляется отдельной посылкой. Если в одном заказе сусаль и другие товары, то посылки будет две. Обе доставки оплачивает получатель.</em></strong></span></p>\r\n<p><span><em>5 листов (достаются из стандартной 25-листовой книги и помещаются в упаковочный материал).</em>  Размер листа 80 х 80 мм, 12 карат (пятисотая проба). Трансферное белое золото отличается от свободного тем, что листы золота нанесены давлением на неприкреплённый к книге отдельный лист пергаментной бумаги. Листы золота легко отделяются от несущего пергаментного листа при приклеивании, но держатся достаточно хорошо. Золото удобно перемещать и разрезать непосредственно на несущем листе. </span>Итальянский производитель Густо Манетти.</p>\r\n<p>Белое сусальное золото не является в действительности совершенно белым, а имеет цвет близкий к серебру с желтоватым оттенком.</p>\r\n<p><span>Сусальное золото купить онлайн в Киеве, Одессе, Харькове, Львове, Днепропетровске, всех городах Украины по хорошей цене (отправка Новой почтой).<br /><br /><img style="display: block; margin-left: auto; margin-right: auto;" src="{{media url=&quot;images/manetti-zoloto-v-raznom-formate.jpg&quot;}}" alt="Сравнить золото Манетти" width="600" /><br /></span></p>',
  'dlina': null,
  'dlina_value': null,
  'gift_message_available': 2,
  'glue_type': null,
  'glue_type_value': null,
  'has_options': 0,
  'image': 'no_selection',
  'image_label': null,
  'is_default_selected': null,
  'is_general_discount_applicable': 452,
  'is_general_discount_applicable_value': 'Нет',
  'leaf_quantity': 444,
  'leaf_quantity_value': '5',
  'leaf_size': 447,
  'leaf_size_value': '80 х 80 мм',
  'leaf_thickness': null,
  'leaf_thickness_value': null,
  'ligaturnyi_ves': 481,
  'ligaturnyi_ves_value': '0.9 гр',
  'links_exist': null,
  'links_purchased_separately': null,
  'links_title': null,
  'manufacturer': 106,
  'manufacturer_value': 'Манетти (Manetti)',
  'metallicheskij_pigment_renesan': null,
  'metallicheskij_pigment_renesan_value': null,
  'msrp': null,
  'msrp_display_actual_price_type': null,
  'name': 'Сусаль трансферная белая, 12к, 5 листов, 80 x 80 мм, Манетти (Manetti)',
  'news_from_date': null,
  'news_to_date': null,
  'nomer': null,
  'nomer_value': null,
  'packing_material': null,
  'packing_material_value': null,
  'potal_format_upakovki': 313,
  'potal_format_upakovki_value': 'Книга',
  'potal_transfernaya_svobodnaya': 311,
  'potal_transfernaya_svobodnaya_value': 'Трансферная',
  'price': 173,
  'price_type': null,
  'price_view': null,
  'product_line': null,
  'product_line_value': null,
  'required_options': 0,
  'shape': null,
  'shape_value': null,
  'short_description': '<span>Трансферное сусальное золото белое 12 карат. 5 листов. Производитель Giusto Manetti, Италия. Размер листа 80 х 80 мм</span>',
  'size': null,
  'size_value': null,
  'sku': 'K00882',
  'sku_type': null,
  'small_image': 'no_selection',
  'small_image_label': null,
  'special_from_date': null,
  'special_price': null,
  'special_to_date': null,
  'swatch_image': 'no_selection',
  'tax_class_id': 2,
  'thumbnail': 'no_selection',
  'thumbnail_label': null,
  'ts_dimensions_height': null,
  'ts_dimensions_length': null,
  'ts_dimensions_width': null,
  'type_oil_glue': null,
  'type_oil_glue_value': null,
  'updated_at': '2020-01-18 22:07:42',
  'url_key': 'manetti-susalnoe-zoloto-transfernoe-beloe-5-listov-80-80-mm',
  'url_path': null,
  'uroven_bleska_gloss': null,
  'uroven_bleska_gloss_value': null,
  'varnish_type': null,
  'varnish_type_value': null,
  'visibility': 4,
  'volume': null,
  'volume_value': null,
  'weight': null,
  'weight_type': null,
  'width': null,
  'width_value': null
};
